### ISSUE TITLE
stringerFramePositionType 

### ISSUE THREAD

**Issue by kngbuzzo** [DLR-LY/CPACS#480]

**Comment by kngbuzzo** [comment]
Another point to consider is that profiles may (but need not) consist of multiple definition vectors. Thus, given at least two stringer/frame's definition vector along with some information on the continuity of the points and vectors (though I'm not sure how exctly these are covered by the continuity and interpolation parameters), the definition of unique planes is basically possible as outlined in the figure below:

![stringer_continuity](https://cloud.githubusercontent.com/assets/16652793/23069230/f22b4eee-f526-11e6-8e0b-b1a42e2402b8.png)

While this method works decently for stringer definitions commonly found in CPACS files (which usually have multiple positions) and continuities >C0, it still misses information in the C0/C0 case on the exact extrusion direction of the plane. A possible way to accomplish this, might be to use the reference point of the second position vector as an orientation node (which boils down to point continuity being increased to 1; also, this implies that two successive vectors must not be collinear). However, for most current CPACS datasets, this approach will not yield planes oriented along the x axis.

I also found, that the current definition for a frame in CPACS requires at least 1 occurrence of framePosition, which should, I guess, be bumped up to 2 for any of the above to work.

**Comment by rmaierl** [comment]
I do not really get your concerns with the stringer-frame-positionings.

Is it an advantage, if stringer can only be defined frame dependent?

We implemented the geometric representation of stringer an frames in our program and the stringer/frame planes are, in general, not coordinate dependent. They are always the connection of adjacent positionings, except a frame with one positioning.

Our main concern was always the absolute values for the input, but the support for a parametrized solution in CPACS was too low.

The figures show the geometric implementation of the stringer frame positioning and a geometry example.

![framexposition](https://cloud.githubusercontent.com/assets/10923333/23070952/12b365ec-f52d-11e6-96e2-37a3867f3cee.JPG)
![frameyzposition](https://cloud.githubusercontent.com/assets/10923333/23070953/12c0e49c-f52d-11e6-81af-2df06865baf5.JPG)


![fuselageframes](https://cloud.githubusercontent.com/assets/10923333/23070941/050bd924-f52d-11e6-9210-b0971d392269.png)

**Comment by kngbuzzo** [comment]
@rmaierl I understand that the positioning sort of works for our current models, but only because we add information implicitly. My concern is, that - even though they are the same data type namely stringerFramePositionType - the information we add is different depending on whether it is a frame or a stringer.
In your example, frames are basically used as providers of an x position at which the 'stringer function' along the fuselage length must be evaluated to get the intersection points. The frame's referenceAngle entry is essentially meaningless. There is a [paper by Scherer][1], where this is explained in great detail. However, to me, assuming frames to be parallel to the yz plane is an inherently rigid definition and not really in sync with the spirit of CPACS, which is why I opened this issue.
Just imagine you wanted to try out tilting your frame planes around the y-axis in the rear conic section in your model. Regardless of wheter it's particularly sensible, it's still a very simple idea, except CPACS will make you jump through hoops to do it.
What exactly do you mean by parametrized solution?
[1]: http://elib.dlr.de/104103/

**Comment by codingpoets** [comment]
If our current definition is too rigid to define less conventional setups I agree that we should adapt.

Can you explain how you would implement this? Which parts of the schema would you change and how, in order to implement your suggestion?

**Comment by sdeinert** [comment]
Your point
> The frame's referenceAngle entry is essentially meaningless

is not exactly true. The way it is currently implemented in our program (as @rmaierl described) is that a frame with one position only uses the x-position creating a full ring around the fuselage's circumference. However, defining more than one position with different angles allows creating partial frames that do not cover the entire circumference. Also, using different x-positions for those multiple positions in one frame allows defining non-planar frames (regardless of their usefulness).

The issue about having a parametrized solution from our point of view is that all structural components in the fuselage are defined using absolute coordinates instead of relative ones (such as eta/xsi in the wing) this makes parametric adjustments to the fuselage difficult, as any adjustment most likely breaks the logic of the internal structure.

Another issue is that stringerFramePositions are all defined inside a stringer or a frame definition even though both components use the same definition. This makes explicit intersections between the two components rather difficult, as a stringer cannot "see" the position of a frame and vice versa. Why don't we pull out the stringerFramePositions from those sub-components and store them somewhere general inside the fuselage or fuselage/structure definition. This way, they would function as a general possibility to define positions inside a fuselage and could be referenced by multiple components at the same time. Through this, one could define a common position referenced by a frame and a stringer to explicitly define an intersection at that point. These general positions could then also be used by any other type of component that needs a positioning/location inside the fuselage.

Additionally it would be helpful to define these positions explicitly inside a fuselage section plane. Currently this is only possible by exactly finding the corresponding x-position of a fuselage section. But again, this is rather crude relying on coordinate precision instead of explicitly stating that the position should lie inside an existing section plane.

Sorry for the unsorted list of suggestions, but the stringerFramePositions have also been a long standing topic of discussion on our side :-)

**Comment by jnwalther** [comment]
Thanks @MarAlder for the reminder that this issue still exists. :)

To everyone else, thanks for the inputs! I will try to summarize the main points discussed here:

- [ ] For the case of point continuity C0, it is unclear in which direction the definition plane should be extruded. The implicit assumption for stringers is an extrusion along the x-axis, whereas for frames it is a rotation around the x axis. Explicit is better than implicit.
- [ ] Tilted frames can somehow be modeled using multiple positions (thanks @sdeinert ).
- [ ] The reference angle for frames may be useful for partial frame definitions (more thanks @sdeinert ). Should we make it optional then? Or could there be an advantage to have it provide a zero circumferential coordinate for the frame? To be honest, I don't have a strong opinion either way, so we may aswell just leave it in.
- [ ] The parametric vs. absolute debate has been going on for a long time with good arguments on either side. However, I don't think that it relates directly to this issue, so I would propose opening a separate issue to deal with that.

As far as I'm concerned, that only leaves the first point to be addressed. A minimal solution would be to put the implicit assumtion in the documentation and be done. Otherwise, picking C0 point continuity should trigger the need for additional nodes namely an `axis` and an `extrusionType`, which can be either `extrusion` along or `rotation` around the axis. Not really sure how to do that in XML, though...
